apiVersion: batch/v1
kind: CronJob
metadata:
  name: internet-monitor
  namespace: monitoring
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: speedtest
            image: <IMAGE_URL>
          restartPolicy: OnFailure